In [3]:
# Step 1: Import required libraries
import numpy as np
import pandas as pd

# Import dataset loader from Scikit-learn
from sklearn import datasets

# Import function to split dataset into training and testing
from sklearn.model_selection import train_test_split

# Import Support Vector Machine classifier
from sklearn.svm import SVC

# Import evaluation metrics
from sklearn.metrics import accuracy_score, classification_report


# Step 2: Load the Iris dataset
iris = datasets.load_iris()

# Step 3: Store feature data (sepal length, sepal width, petal length, petal width)
X = iris.data

# Step 4: Store target labels (0 = Setosa, 1 = Versicolor, 2 = Virginica)
y = iris.target


# Step 5: Display basic dataset information
print("Dataset Shape:", X.shape)
print("First 5 rows of features:\n", X[:5])
print("Target values:\n", y[:5])


# Step 6: Split dataset into training and testing data
# 80% training data and 20% testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("\nTraining Data Size:", X_train.shape)
print("Testing Data Size:", X_test.shape)


# Step 7: Create the SVM classifier
# kernel='linear' means we use a linear decision boundary
svm_classifier = SVC(kernel='linear')


# Step 8: Train the model using training data
svm_classifier.fit(X_train, y_train)


# Step 9: Predict the output for testing data
y_pred = svm_classifier.predict(X_test)


# Step 10: Evaluate the model performance
accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)


# Step 11: Print classification report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


# Step 12: Predict a new sample (example flower measurement)
sample = [[5.1, 3.5, 1.4, 0.2]]
prediction = svm_classifier.predict(sample)

print("\nPrediction for sample", sample, "is class:", prediction)

Dataset Shape: (150, 4)
First 5 rows of features:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Target values:
 [0 0 0 0 0]

Training Data Size: (120, 4)
Testing Data Size: (30, 4)

Model Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Prediction for sample [[5.1, 3.5, 1.4, 0.2]] is class: [0]
